"""initial schema

Revision ID: 292dca519d88
Revises:
Create Date: 2026-07-24 15:26:06.537812+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '292dca519d88'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('old_content_hash', sa.String(length=64), nullable=True),
    sa.Column('new_content_hash', sa.String(length=64), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=False),
    sa.Column('git_commit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_author', sa.String(length=128), nullable=True),
    sa.Column('commit_message', sa.String(length=512), nullable=True),
    sa.Column('affected_relations', sa.Integer(), nullable=False),
    sa.Column('rollback_source_commit', sa.String(length=40), nullable=True),
    sa.Column('is_rollback_related', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_change_history'))
    )
    op.create_index('idx_history_chunk', 'change_history', ['chunk_id'], unique=False)
    op.create_index('idx_history_commit', 'change_history', ['git_commit_hash'], unique=False)
    op.create_index('idx_history_rollback', 'change_history', ['rollback_source_commit'], unique=False, postgresql_where='rollback_source_commit IS NOT NULL')
    op.create_index('idx_history_time', 'change_history', ['git_commit_time'], unique=False, postgresql_using='btree')
    op.create_index('idx_history_type', 'change_history', ['change_type'], unique=False)
    op.create_table('chunk_relations',
    sa.Column('relation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('target_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('anchor_key', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('relation_id', name=op.f('pk_chunk_relations')),
    sa.UniqueConstraint('source_chunk_id', 'target_chunk_id', 'relation_type', name='uk_relation')
    )
    op.create_index('idx_relations_active', 'chunk_relations', ['is_stale'], unique=False, postgresql_where='is_stale = false')
    op.create_index('idx_relations_anchor', 'chunk_relations', ['anchor_key'], unique=False)
    op.create_index('idx_relations_source', 'chunk_relations', ['source_chunk_id'], unique=False)
    op.create_index('idx_relations_target', 'chunk_relations', ['target_chunk_id'], unique=False)
    op.create_index('idx_relations_type', 'chunk_relations', ['relation_type'], unique=False)
    op.create_table('code_files',
    sa.Column('file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('package_name', sa.String(length=256), nullable=True),
    sa.Column('module_name', sa.String(length=128), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('last_commit', sa.String(length=40), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_code_files')),
    sa.UniqueConstraint('file_path', name=op.f('uk_code_files_file_path'))
    )
    op.create_index('idx_code_files_module', 'code_files', ['module_name'], unique=False)
    op.create_index('idx_code_files_package', 'code_files', ['package_name'], unique=False)
    op.create_table('doc_files',
    sa.Column('file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('last_commit', sa.String(length=40), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('total_tables', sa.Integer(), nullable=True),
    sa.Column('parse_engine', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('ocr_required', sa.Boolean(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_doc_files')),
    sa.UniqueConstraint('file_path', name=op.f('uk_doc_files_file_path'))
    )
    op.create_index('idx_doc_files_format', 'doc_files', ['file_format'], unique=False)
    op.create_table('graph_communities',
    sa.Column('community_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('member_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_embedding_synced', sa.Boolean(), nullable=False),
    sa.Column('computed_at_commit', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('community_id', name=op.f('pk_graph_communities'))
    )
    op.create_index('idx_community_level', 'graph_communities', ['level'], unique=False)
    op.create_table('ranking_model_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('semantic_weight', sa.Float(), nullable=False),
    sa.Column('graph_weight', sa.Float(), nullable=False),
    sa.Column('structural_weight', sa.Float(), nullable=False),
    sa.Column('min_score_threshold', sa.Float(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_ranking_model_config'))
    )
    op.create_table('retrieval_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('recall_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=True),
    sa.Column('coarse_rank_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coarse_rank_count', sa.Integer(), nullable=True),
    sa.Column('fine_rank_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fine_rank_count', sa.Integer(), nullable=True),
    sa.Column('final_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_feedback', sa.String(length=32), nullable=True),
    sa.Column('feedback_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recall_latency_ms', sa.Integer(), nullable=True),
    sa.Column('coarse_rank_ms', sa.Integer(), nullable=True),
    sa.Column('fine_rank_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_retrieval_logs'))
    )
    op.create_index('idx_retrieval_logs_feedback', 'retrieval_logs', ['user_feedback'], unique=False, postgresql_where='user_feedback IS NOT NULL')
    op.create_index('idx_retrieval_logs_time', 'retrieval_logs', ['created_at'], unique=False)
    op.create_table('rollback_history',
    sa.Column('rollback_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rollback_commit', sa.String(length=40), nullable=False),
    sa.Column('source_commit', sa.String(length=40), nullable=False),
    sa.Column('chunks_rolled_back', sa.Integer(), nullable=False),
    sa.Column('chunks_restored', sa.Integer(), nullable=False),
    sa.Column('chunks_deleted', sa.Integer(), nullable=False),
    sa.Column('relations_restored', sa.Integer(), nullable=False),
    sa.Column('anchors_restored', sa.Integer(), nullable=False),
    sa.Column('stale_anchors_cleared', sa.Integer(), nullable=False),
    sa.Column('doc_pr_closed', sa.String(length=512), nullable=True),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rollback_id', name=op.f('pk_rollback_history'))
    )
    op.create_index('idx_rollback_commit', 'rollback_history', ['rollback_commit'], unique=False)
    op.create_index('idx_rollback_source', 'rollback_history', ['source_commit'], unique=False)
    op.create_table('sync_tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('chunks_added', sa.Integer(), nullable=False),
    sa.Column('chunks_modified', sa.Integer(), nullable=False),
    sa.Column('chunks_deleted', sa.Integer(), nullable=False),
    sa.Column('relations_updated', sa.Integer(), nullable=False),
    sa.Column('vector_sync_status', sa.String(length=32), nullable=False),
    sa.Column('graph_update_status', sa.String(length=32), nullable=False),
    sa.Column('doc_pr_url', sa.String(length=512), nullable=True),
    sa.Column('doc_pr_status', sa.String(length=32), nullable=True),
    sa.Column('change_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_sync_tasks'))
    )
    op.create_index('idx_sync_tasks_commit', 'sync_tasks', ['commit_hash'], unique=False)
    op.create_index('idx_sync_tasks_status', 'sync_tasks', ['status'], unique=False)
    op.create_table('code_chunks',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('method_name', sa.String(length=256), nullable=True),
    sa.Column('method_signature', sa.String(length=512), nullable=True),
    sa.Column('access_modifier', sa.String(length=32), nullable=True),
    sa.Column('return_type', sa.String(length=256), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('javadoc', sa.Text(), nullable=True),
    sa.Column('inline_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('implements_interface', sa.String(length=256), nullable=True),
    sa.Column('extends_class', sa.String(length=256), nullable=True),
    sa.Column('type_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_doc_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_anchor_key', sa.String(length=512), nullable=True),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=False),
    sa.Column('git_commit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at_commit', sa.String(length=40), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['code_files.file_id'], name=op.f('fk_code_chunks_file_id_code_files')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_code_chunks'))
    )
    op.create_index('idx_code_chunks_active', 'code_chunks', ['is_deleted'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('idx_code_chunks_anchor', 'code_chunks', ['code_anchor_key'], unique=False)
    op.create_index('idx_code_chunks_class', 'code_chunks', ['class_name'], unique=False)
    op.create_index('idx_code_chunks_commit', 'code_chunks', ['git_commit_hash'], unique=False)
    op.create_index('idx_code_chunks_file', 'code_chunks', ['file_id'], unique=False)
    op.create_index('idx_code_chunks_hash', 'code_chunks', ['content_hash'], unique=False)
    op.create_index('idx_code_chunks_keywords', 'code_chunks', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_code_chunks_method', 'code_chunks', ['method_name'], unique=False)
    op.create_index('idx_code_chunks_type', 'code_chunks', ['chunk_type'], unique=False)
    op.create_table('doc_chunks',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('heading_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('heading_level', sa.SmallInteger(), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('code_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_code_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inline_code_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stale_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=False),
    sa.Column('git_commit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at_commit', sa.String(length=40), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_synced', sa.Boolean(), nullable=False),
    sa.Column('chunk_content_type', sa.String(length=32), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('image_thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('image_description', sa.Text(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('image_caption', sa.String(length=512), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_html', sa.Text(), nullable=True),
    sa.Column('table_description', sa.Text(), nullable=True),
    sa.Column('table_total_rows', sa.Integer(), nullable=True),
    sa.Column('table_total_cols', sa.Integer(), nullable=True),
    sa.Column('is_table_fragment', sa.Boolean(), nullable=True),
    sa.Column('table_fragment_index', sa.Integer(), nullable=True),
    sa.Column('parent_table_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['doc_files.file_id'], name=op.f('fk_doc_chunks_file_id_doc_files')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_doc_chunks'))
    )
    op.create_index('idx_doc_chunks_active', 'doc_chunks', ['is_deleted'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('idx_doc_chunks_anchors', 'doc_chunks', ['code_anchors'], unique=False, postgresql_using='gin')
    op.create_index('idx_doc_chunks_content_type', 'doc_chunks', ['chunk_content_type'], unique=False)
    op.create_index('idx_doc_chunks_file', 'doc_chunks', ['file_id'], unique=False)
    op.create_index('idx_doc_chunks_hash', 'doc_chunks', ['content_hash'], unique=False)
    op.create_index('idx_doc_chunks_heading', 'doc_chunks', ['heading_path'], unique=False, postgresql_using='gin')
    op.create_table('node_community_mapping',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('is_centroid', sa.Boolean(), nullable=False),
    sa.Column('pagerank_in_community', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['graph_communities.community_id'], name=op.f('fk_node_community_mapping_community_id_graph_communities')),
    sa.PrimaryKeyConstraint('chunk_id', 'level', name=op.f('pk_node_community_mapping'))
    )
    op.create_index('idx_community_nodes', 'node_community_mapping', ['community_id'], unique=False)
    op.create_index('idx_node_community', 'node_community_mapping', ['chunk_id'], unique=False)
    op.create_table('anchor_mappings',
    sa.Column('mapping_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anchor_key', sa.String(length=512), nullable=False),
    sa.Column('code_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('doc_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by_commit', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_chunk_id'], ['code_chunks.chunk_id'], name=op.f('fk_anchor_mappings_code_chunk_id_code_chunks')),
    sa.ForeignKeyConstraint(['doc_chunk_id'], ['doc_chunks.chunk_id'], name=op.f('fk_anchor_mappings_doc_chunk_id_doc_chunks')),
    sa.PrimaryKeyConstraint('mapping_id', name=op.f('pk_anchor_mappings')),
    sa.UniqueConstraint('anchor_key', 'code_chunk_id', 'doc_chunk_id', name='uk_anchor_pair')
    )
    op.create_index('idx_anchor_active', 'anchor_mappings', ['is_active'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_anchor_code', 'anchor_mappings', ['code_chunk_id'], unique=False)
    op.create_index('idx_anchor_doc', 'anchor_mappings', ['doc_chunk_id'], unique=False)
    op.create_index('idx_anchor_key', 'anchor_mappings', ['anchor_key'], unique=False)
    op.create_table('call_graph',
    sa.Column('edge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('caller_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('callee_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('call_expression', sa.String(length=512), nullable=True),
    sa.Column('call_line', sa.Integer(), nullable=True),
    sa.Column('is_recursive', sa.Boolean(), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['callee_chunk_id'], ['code_chunks.chunk_id'], name=op.f('fk_call_graph_callee_chunk_id_code_chunks')),
    sa.ForeignKeyConstraint(['caller_chunk_id'], ['code_chunks.chunk_id'], name=op.f('fk_call_graph_caller_chunk_id_code_chunks')),
    sa.PrimaryKeyConstraint('edge_id', name=op.f('pk_call_graph')),
    sa.UniqueConstraint('caller_chunk_id', 'callee_chunk_id', 'call_line', name='uk_call_edge')
    )
    op.create_index('idx_call_graph_callee', 'call_graph', ['callee_chunk_id'], unique=False)
    op.create_index('idx_call_graph_caller', 'call_graph', ['caller_chunk_id'], unique=False)
    op.create_table('doc_resources',
    sa.Column('resource_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['doc_chunks.chunk_id'], name=op.f('fk_doc_resources_chunk_id_doc_chunks')),
    sa.ForeignKeyConstraint(['file_id'], ['doc_files.file_id'], name=op.f('fk_doc_resources_file_id_doc_files')),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_doc_resources'))
    )
    op.create_table('graph_embeddings',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('graph_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('node_degree', sa.Integer(), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=False),
    sa.Column('out_degree', sa.Integer(), nullable=False),
    sa.Column('pagerank', sa.Float(), nullable=False),
    sa.Column('betweenness', sa.Float(), nullable=False),
    sa.Column('community_id_l0', sa.BigInteger(), nullable=True),
    sa.Column('community_id_l1', sa.BigInteger(), nullable=True),
    sa.Column('community_id_l2', sa.BigInteger(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['code_chunks.chunk_id'], name=op.f('fk_graph_embeddings_chunk_id_code_chunks')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_graph_embeddings'))
    )
    op.create_index('idx_graph_embed_community_l0', 'graph_embeddings', ['community_id_l0'], unique=False)
    op.create_index('idx_graph_embed_community_l1', 'graph_embeddings', ['community_id_l1'], unique=False)
    op.create_index('idx_graph_embed_pagerank', 'graph_embeddings', ['pagerank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_graph_embed_pagerank', table_name='graph_embeddings')
    op.drop_index('idx_graph_embed_community_l1', table_name='graph_embeddings')
    op.drop_index('idx_graph_embed_community_l0', table_name='graph_embeddings')
    op.drop_table('graph_embeddings')
    op.drop_table('doc_resources')
    op.drop_index('idx_call_graph_caller', table_name='call_graph')
    op.drop_index('idx_call_graph_callee', table_name='call_graph')
    op.drop_table('call_graph')
    op.drop_index('idx_anchor_key', table_name='anchor_mappings')
    op.drop_index('idx_anchor_doc', table_name='anchor_mappings')
    op.drop_index('idx_anchor_code', table_name='anchor_mappings')
    op.drop_index('idx_anchor_active', table_name='anchor_mappings', postgresql_where='is_active = true')
    op.drop_table('anchor_mappings')
    op.drop_index('idx_node_community', table_name='node_community_mapping')
    op.drop_index('idx_community_nodes', table_name='node_community_mapping')
    op.drop_table('node_community_mapping')
    op.drop_index('idx_doc_chunks_heading', table_name='doc_chunks', postgresql_using='gin')
    op.drop_index('idx_doc_chunks_hash', table_name='doc_chunks')
    op.drop_index('idx_doc_chunks_file', table_name='doc_chunks')
    op.drop_index('idx_doc_chunks_content_type', table_name='doc_chunks')
    op.drop_index('idx_doc_chunks_anchors', table_name='doc_chunks', postgresql_using='gin')
    op.drop_index('idx_doc_chunks_active', table_name='doc_chunks', postgresql_where='is_deleted = false')
    op.drop_table('doc_chunks')
    op.drop_index('idx_code_chunks_type', table_name='code_chunks')
    op.drop_index('idx_code_chunks_method', table_name='code_chunks')
    op.drop_index('idx_code_chunks_keywords', table_name='code_chunks', postgresql_using='gin')
    op.drop_index('idx_code_chunks_hash', table_name='code_chunks')
    op.drop_index('idx_code_chunks_file', table_name='code_chunks')
    op.drop_index('idx_code_chunks_commit', table_name='code_chunks')
    op.drop_index('idx_code_chunks_class', table_name='code_chunks')
    op.drop_index('idx_code_chunks_anchor', table_name='code_chunks')
    op.drop_index('idx_code_chunks_active', table_name='code_chunks', postgresql_where='is_deleted = false')
    op.drop_table('code_chunks')
    op.drop_index('idx_sync_tasks_status', table_name='sync_tasks')
    op.drop_index('idx_sync_tasks_commit', table_name='sync_tasks')
    op.drop_table('sync_tasks')
    op.drop_index('idx_rollback_source', table_name='rollback_history')
    op.drop_index('idx_rollback_commit', table_name='rollback_history')
    op.drop_table('rollback_history')
    op.drop_index('idx_retrieval_logs_time', table_name='retrieval_logs')
    op.drop_index('idx_retrieval_logs_feedback', table_name='retrieval_logs', postgresql_where='user_feedback IS NOT NULL')
    op.drop_table('retrieval_logs')
    op.drop_table('ranking_model_config')
    op.drop_index('idx_community_level', table_name='graph_communities')
    op.drop_table('graph_communities')
    op.drop_index('idx_doc_files_format', table_name='doc_files')
    op.drop_table('doc_files')
    op.drop_index('idx_code_files_package', table_name='code_files')
    op.drop_index('idx_code_files_module', table_name='code_files')
    op.drop_table('code_files')
    op.drop_index('idx_relations_type', table_name='chunk_relations')
    op.drop_index('idx_relations_target', table_name='chunk_relations')
    op.drop_index('idx_relations_source', table_name='chunk_relations')
    op.drop_index('idx_relations_anchor', table_name='chunk_relations')
    op.drop_index('idx_relations_active', table_name='chunk_relations', postgresql_where='is_stale = false')
    op.drop_table('chunk_relations')
    op.drop_index('idx_history_type', table_name='change_history')
    op.drop_index('idx_history_time', table_name='change_history', postgresql_using='btree')
    op.drop_index('idx_history_rollback', table_name='change_history', postgresql_where='rollback_source_commit IS NOT NULL')
    op.drop_index('idx_history_commit', table_name='change_history')
    op.drop_index('idx_history_chunk', table_name='change_history')
    op.drop_table('change_history')
    # ### end Alembic commands ###
