"""add conversations and chat_messages

Revision ID: 768492a1d1e5
Revises: 292dca519d88
Create Date: 2026-07-25 13:16:04.296840+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '768492a1d1e5'
down_revision: str | None = '292dca519d88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversations'))
    )
    op.create_index('idx_conversations_agent', 'conversations', ['agent_type'], unique=False)
    op.create_index('idx_conversations_created', 'conversations', ['created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_log_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name=op.f('fk_chat_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['retrieval_log_id'], ['retrieval_logs.log_id'], name=op.f('fk_chat_messages_retrieval_log_id_retrieval_logs')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_messages'))
    )
    op.create_index('idx_chat_messages_conversation', 'chat_messages', ['conversation_id'], unique=False)
    op.create_index('idx_chat_messages_created', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_messages_retrieval', 'chat_messages', ['retrieval_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_retrieval', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created', table_name='chat_messages')
    op.drop_index('idx_chat_messages_conversation', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_conversations_created', table_name='conversations')
    op.drop_index('idx_conversations_agent', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
