"""M21 add commit_sha to doc_update_proposals

Revision ID: 14d0bbf2b0ab
Revises: b808ee2b85ce
Create Date: 2026-08-06 05:49:23.127166+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14d0bbf2b0ab'
down_revision: str | None = 'b808ee2b85ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_update_proposals', sa.Column('commit_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_update_proposals', 'commit_sha')
    # ### end Alembic commands ###
