"""m15 doc update proposals

Revision ID: b808ee2b85ce
Revises: f4a2c7e91b38
Create Date: 2026-08-05 13:12:34.159952+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b808ee2b85ce'
down_revision: str | None = 'f4a2c7e91b38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_update_proposals',
    sa.Column('proposal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('heading_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('rewritten_text', sa.Text(), nullable=True),
    sa.Column('artifact_key', sa.String(length=512), nullable=True),
    sa.Column('branch_name', sa.String(length=256), nullable=True),
    sa.Column('commit_message', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('source_commit', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['doc_files.file_id'], name=op.f('fk_doc_update_proposals_file_id_doc_files')),
    sa.PrimaryKeyConstraint('proposal_id', name=op.f('pk_doc_update_proposals'))
    )
    op.create_index('idx_doc_proposals_conv', 'doc_update_proposals', ['conversation_id'], unique=False)
    op.create_index('idx_doc_proposals_file', 'doc_update_proposals', ['file_id'], unique=False)
    op.create_index('idx_doc_proposals_status', 'doc_update_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_proposals_status', table_name='doc_update_proposals')
    op.drop_index('idx_doc_proposals_file', table_name='doc_update_proposals')
    op.drop_index('idx_doc_proposals_conv', table_name='doc_update_proposals')
    op.drop_table('doc_update_proposals')
    # ### end Alembic commands ###
